const MESSAGES: Record<string, string> = {
  UNAUTHORIZED: "Connecte-toi pour continuer.",
  FORBIDDEN: "Accès refusé.",
  ACCOUNT_SUSPENDED: "Ce compte est suspendu.",
  USER_NOT_FOUND: "Compte introuvable.",
  INSUFFICIENT_MINTS: "Il te faut 1 Mint pour générer une affiche.",
  PLAN_INVALID: "Cette offre n’est plus disponible.",
  PAYMENT_INIT_FAILED: "Le paiement n’a pas pu démarrer. Réessaie.",
  PAYMENT_NOT_FOUND: "Paiement introuvable.",
  PAYMENT_NOT_DISCARDABLE: "Ce paiement a déjà crédité des Mints, ou il n’est plus en attente.",
  MONEY_FUSION_API_URL_MISSING: "Le paiement n’est pas encore configuré.",
  NEXT_PUBLIC_APP_URL_MISSING: "L’adresse du site n’est pas configurée.",
  RODIUMAI_API_KEY_MISSING: "La génération n’est pas disponible pour le moment.",
  RODIUM_UNAVAILABLE: "La génération n’est pas disponible pour le moment.",
  RODIUM_NO_IMAGE_MODEL: "Aucun modèle image n’est disponible actuellement.",
  GENERATION_FAILED: "La génération a échoué. Ton Mint n’a pas été débité.",
  INVALID_IMAGE: "L’image fournie n’est pas valide (JPG, PNG ou WEBP, 2 Mo max).",
  INVALID_PHONE: "Le numéro de téléphone n’est pas valide.",
  INVALID_EMAIL: "L’e-mail n’est pas valide.",
  RATE_LIMITED: "Trop de tentatives. Réessaie dans un instant.",
  EXPORT_LOCKED: "L’export éditable n’est pas inclus dans tes offres.",
  NOT_FOUND: "Ressource introuvable.",
  INVALID_MINT_AMOUNT: "La quantité doit être un entier dans la limite autorisée.",
  REASON_REQUIRED: "Le motif est obligatoire.",
  BALANCE_WOULD_BE_NEGATIVE: "Le solde ne peut pas devenir négatif.",
  GRANT_NOT_PENDING: "Cette attribution n’est plus en attente.",
  EXACT_COPY_NO_REFERENCE: "Aucune référence réelle n’est disponible dans le domaine choisi.",
  EXACT_COPY_REFERENCE_MISSING: "La copie exacte n’a pas pu charger l’image de référence.",
  EXACT_COPY_WRONG_MODEL: "La copie exacte exige le modèle image demandé.",
  PERSONAL_REFERENCE_LOCKED: "La référence personnelle est réservée aux packs 20 000 et 25 000 FCFA.",
  REFERENCE_LIBRARY_UNAVAILABLE: "La bibliothèque de références n’est pas disponible.",
  REFERENCE_DOWNLOAD_FAILED: "L’image de référence n’a pas pu être lue.",
  REFERENCE_PATH_INVALID: "Le chemin de la référence n’est pas valide.",
  INVALID_SUPPORT: "Le ticket n’est pas valide. Vérifie le sujet, la catégorie et le message.",
  INVALID_ATTACHMENT: "La pièce jointe doit être une image JPG, PNG ou WEBP de 2 Mo maximum.",
  ATTACHMENT_LIMIT: "Ce ticket a déjà le nombre maximum de pièces jointes.",
  SUPPORT_SEQUENCE_FAILED: "Le numéro de ticket n’a pas pu être attribué.",
  PROMO_INVALID: "Ce code promo n’est pas valide.",
  PROMO_NOT_FOUND: "Ce code promo n’existe pas.",
  PROMO_INACTIVE: "Ce code promo n’est plus actif.",
  PROMO_ALREADY_USED: "Tu as déjà utilisé ce code.",
  PROMO_EXHAUSTED: "Ce code a atteint son nombre d’utilisations.",
  PROMO_TAKEN: "Ce code existe déjà.",
};

export function publicErrorMessage(error: unknown) {
  const code = error instanceof Error ? error.message : "UNKNOWN";
  if (MESSAGES[code]) return MESSAGES[code];
  if (code.startsWith("RODIUM_")) return MESSAGES.RODIUM_UNAVAILABLE;
  return "Une erreur est survenue. Réessaie dans un instant.";
}
