export const EXACT_SHOWCASE = [
  {
    id: "exact-beaute",
    src: "/creations/exact-beaute.webp",
    width: 736,
    height: 1040,
    title: "Black is Beauty",
    subtitle: "Beauté",
    meta: "Date retirée",
    cta: "Exemple public",
    domaine: "Beauté",
    alt: "Exemple public, affiche beauté. Visages, date et nom retirés.",
    className: "cover-side cover-side-left",
    priority: false,
  },
  {
    id: "exact-gadgets",
    src: "/creations/exact-gadgets.webp",
    width: 736,
    height: 736,
    title: "Shop your gadgets",
    subtitle: "High-tech",
    meta: "Contact retiré",
    cta: "Shop Now",
    domaine: "High-tech",
    alt: "Exemple public, affiche high-tech. Visage, marque et contacts retirés.",
    className: "cover-side cover-side-right",
    priority: false,
  },
  {
    id: "exact-retrouvailles",
    src: "/creations/exact-retrouvailles.webp",
    width: 736,
    height: 943,
    title: "Retrouvailles",
    subtitle: "Événement",
    meta: "Salle Horizon",
    cta: "Réservation",
    domaine: "Événement",
    alt: "Exemple public, affiche événement. Visages, horaire, lieu et téléphones retirés.",
    className: "cover-hero",
    priority: true,
  },
] as const;
