export const EXACT_SHOWCASE = [
  {
    id: "exact-beaute",
    src: "/creations/exact-beaute.webp",
    width: 736,
    height: 1040,
    title: "Black is Beauty",
    subtitle: "Olulite",
    meta: "Saturday, 15 August, 2026",
    cta: "Olulite graphics",
    domaine: "Beauté",
    alt: "Copie exacte, affiche Black is Beauty, même photo, même texte, même police, même fond.",
    className: "cover-side cover-side-left",
    priority: false,
  },
  {
    id: "exact-gadgets",
    src: "/creations/exact-gadgets.webp",
    width: 736,
    height: 736,
    title: "Shop your gadgets",
    subtitle: "Castro mobile world",
    meta: "07041838267",
    cta: "Shop Now",
    domaine: "High-tech",
    alt: "Copie exacte, affiche Shop your gadgets, même photo, même texte, même police, même fond.",
    className: "cover-side cover-side-right",
    priority: false,
  },
  {
    id: "exact-retrouvailles",
    src: "/creations/exact-retrouvailles.webp",
    width: 736,
    height: 943,
    title: "Retrouvailles",
    subtitle: "Chaque dimanche 14h00",
    meta: "JKK Lodge 1, 27eme poteaux route Kinsevere",
    cta: "Réservation",
    domaine: "Événement",
    alt: "Copie exacte, affiche Retrouvailles, même photo, même texte, même police, même fond.",
    className: "cover-hero",
    priority: true,
  },
] as const;
